const fs = require('fs');

const data = {
  Indonesia: {
    // Shared
    Dashboard: "Dashboard", Ticket: "Tiket", "Recurring Task": "Tugas Rutin", Laporan: "Laporan", "Knowledge Base": "Basis Pengetahuan", PIC: "PIC", "Chatbot AI": "Chatbot AI", Pengaturan: "Pengaturan", Keluar: "Keluar",
    "Tiket Aktif": "Tiket Aktif", "Tiket Selesai": "Tiket Selesai", "Prioritas Tinggi": "Prioritas Tinggi", "Total Laporan": "Total Laporan", "Distribusi Prioritas": "Distribusi Prioritas", "Riwayat Aktivitas Terkini": "Riwayat Aktivitas Terkini", "Ticket Terbaru": "Tiket Terbaru",
    "Preferensi Tampilan": "Preferensi Tampilan", Tema: "Tema", Terang: "Terang", Gelap: "Gelap", "Bahasa Aplikasi": "Bahasa Aplikasi", "Notifikasi Sistem": "Notifikasi Sistem", "Data & Aplikasi": "Data & Aplikasi", "Tentang Aplikasi": "Tentang Aplikasi", Reset: "Reset", Bersihkan: "Bersihkan",
    "Welcome,": "Selamat datang,", "IT Application Support Team": "Tim Dukungan Aplikasi IT", "Progress Pekerjaan Tim IT Application Support": "Progress Pekerjaan Tim IT Application Support", "Quick Actions": "Aksi Cepat", "Buat Ticket": "Buat Tiket Baru", "Lihat Semua": "Lihat Semua", "Semua Status": "Semua Status", "To Do": "To Do", "On Progress": "On Progress", "Completed": "Selesai", "Semua Prioritas": "Semua Prioritas", "High": "Tinggi", "Medium": "Sedang", "Low": "Rendah", "Cari tiket...": "Cari tiket...", "Judul Tiket": "Judul Tiket", "Layanan": "Layanan", "Status": "Status", "Prioritas": "Prioritas", "Dibuat": "Dibuat", "Loading tickets...": "Memuat tiket...", "Tidak ada tiket ditemukan": "Tidak ada tiket ditemukan", "Belum di-assign": "Belum di-assign", "Menampilkan": "Menampilkan", "dari": "dari", "tiket": "tiket", "Sen": "Sen", "Sel": "Sel", "Rab": "Rab", "Kam": "Kam", "Jum": "Jum", "Sab": "Sab", "Min": "Min", "Agenda": "Agenda", "agenda": "agenda", "Tidak ada tiket dibuat": "Tidak ada tiket dibuat", "Pilih tanggal lain atau buat tiket baru.": "Pilih tanggal lain atau buat tiket baru.", "Task diselesaikan": "Tugas diselesaikan", "Task diproses": "Tugas diproses", "Prioritas tinggi": "Prioritas tinggi", "Ticket baru / To Do": "Tiket baru / To Do", "Tinggi": "Tinggi", "Sedang": "Sedang", "Rendah": "Rendah",
    // Laporkan Kendala specific
    "Manajemen Tiket": "Manajemen Tiket", "Daftar seluruh tiket aktif dan riwayat penyelesaian.": "Daftar seluruh tiket aktif dan riwayat penyelesaian.", "Refresh Data": "Refresh Data", "Buat Tiket Baru": "Buat Tiket Baru", "Selesai": "Selesai", "Cari subject, deskripsi, atau ID...": "Cari subject, deskripsi, atau ID...", "Semua Layanan": "Semua Layanan", "Semua PIC": "Semua PIC", "Subject": "Subjek", "Aksi": "Aksi", "Tidak ada tiket yang ditemukan.": "Tidak ada tiket yang ditemukan.", "Coba sesuaikan filter atau pencarian Anda.": "Coba sesuaikan filter atau pencarian Anda.", "Lihat Solusi": "Lihat Solusi", "Selesaikan Tiket": "Selesaikan Tiket", "Tiket yang sudah selesai tidak dapat diedit": "Tiket yang sudah selesai tidak dapat diedit", "Edit Ticket": "Edit Tiket", "Hapus Tiket": "Hapus Tiket", "Tidak ada deskripsi": "Tidak ada deskripsi", "Tanggal": "Tanggal", "Tiket To Do": "Tiket To Do", "Tiket belum/sedang penanganan": "Tiket belum/sedang penanganan", "Total tiket diselesaikan": "Total tiket diselesaikan", "Butuh tindakan segera": "Butuh tindakan segera", "Keseluruhan tiket": "Keseluruhan tiket"
  },
  Inggris: {
    Dashboard: "Dashboard", Ticket: "Ticket", "Recurring Task": "Recurring Task", Laporan: "Reports", "Knowledge Base": "Knowledge Base", PIC: "Assignee", "Chatbot AI": "AI Chatbot", Pengaturan: "Settings", Keluar: "Logout",
    "Tiket Aktif": "Active Tickets", "Tiket Selesai": "Completed Tickets", "Prioritas Tinggi": "High Priority", "Total Laporan": "Total Reports", "Distribusi Prioritas": "Priority Distribution", "Riwayat Aktivitas Terkini": "Recent Activity", "Ticket Terbaru": "Latest Tickets",
    "Preferensi Tampilan": "Display Preferences", Tema: "Theme", Terang: "Light", Gelap: "Dark", "Bahasa Aplikasi": "Application Language", "Notifikasi Sistem": "System Notifications", "Data & Aplikasi": "Data & App", "Tentang Aplikasi": "About App", Reset: "Reset", Bersihkan: "Clear",
    "Welcome,": "Welcome,", "IT Application Support Team": "IT Application Support Team", "Progress Pekerjaan Tim IT Application Support": "IT Application Support Team Work Progress", "Quick Actions": "Quick Actions", "Buat Ticket": "Create Ticket", "Lihat Semua": "View All", "Semua Status": "All Statuses", "To Do": "To Do", "On Progress": "In Progress", "Completed": "Completed", "Semua Prioritas": "All Priorities", "High": "High", "Medium": "Medium", "Low": "Low", "Cari tiket...": "Search tickets...", "Judul Tiket": "Ticket Title", "Layanan": "Service", "Status": "Status", "Prioritas": "Priority", "Dibuat": "Created", "Loading tickets...": "Loading tickets...", "Tidak ada tiket ditemukan": "No tickets found", "Belum di-assign": "Unassigned", "Menampilkan": "Showing", "dari": "of", "tiket": "tickets", "Sen": "Mon", "Sel": "Tue", "Rab": "Wed", "Kam": "Thu", "Jum": "Fri", "Sab": "Sat", "Min": "Sun", "Agenda": "Agenda", "agenda": "agenda(s)", "Tidak ada tiket dibuat": "No tickets created", "Pilih tanggal lain atau buat tiket baru.": "Select another date or create a new ticket.", "Task diselesaikan": "Task completed", "Task diproses": "Task in progress", "Prioritas tinggi": "High priority", "Ticket baru / To Do": "New ticket / To Do", "Tinggi": "High", "Sedang": "Medium", "Rendah": "Low",
    "Manajemen Tiket": "Ticket Management", "Daftar seluruh tiket aktif dan riwayat penyelesaian.": "List of all active tickets and completion history.", "Refresh Data": "Refresh Data", "Buat Tiket Baru": "Create New Ticket", "Selesai": "Completed", "Cari subject, deskripsi, atau ID...": "Search subject, description, or ID...", "Semua Layanan": "All Services", "Semua PIC": "All PICs", "Subject": "Subject", "Aksi": "Action", "Tidak ada tiket yang ditemukan.": "No tickets found.", "Coba sesuaikan filter atau pencarian Anda.": "Try adjusting your filters or search.", "Lihat Solusi": "View Resolution", "Selesaikan Tiket": "Resolve Ticket", "Tiket yang sudah selesai tidak dapat diedit": "Completed tickets cannot be edited", "Edit Ticket": "Edit Ticket", "Hapus Tiket": "Delete Ticket", "Tidak ada deskripsi": "No description", "Tanggal": "Date", "Tiket To Do": "To Do Tickets", "Tiket belum/sedang penanganan": "Tickets waiting or in progress", "Total tiket diselesaikan": "Total completed tickets", "Butuh tindakan segera": "Requires immediate action", "Keseluruhan tiket": "All tickets"
  },
  Arab: {
    Dashboard: "لوحة القيادة", Ticket: "تذكرة", "Recurring Task": "مهمة متكررة", Laporan: "تقارير", "Knowledge Base": "قاعدة المعرفة", PIC: "المسؤول", "Chatbot AI": "روبوت الدردشة", Pengaturan: "إعدادات", Keluar: "تسجيل خروج",
    "Tiket Aktif": "التذاكر النشطة", "Tiket Selesai": "التذاكر المكتملة", "Prioritas Tinggi": "أولوية عالية", "Total Laporan": "إجمالي التقارير", "Distribusi Prioritas": "توزيع الأولويات", "Riwayat Aktivitas Terkini": "النشاط الأخير", "Ticket Terbaru": "أحدث التذاكر",
    "Preferensi Tampilan": "تفضيلات العرض", Tema: "المظهر", Terang: "فاتح", Gelap: "داكن", "Bahasa Aplikasi": "لغة التطبيق", "Notifikasi Sistem": "إشعارات النظام", "Data & Aplikasi": "البيانات والتطبيق", "Tentang Aplikasi": "حول التطبيق", Reset: "إعادة تعيين", Bersihkan: "مسح",
    "Welcome,": "مرحباً،", "IT Application Support Team": "فريق دعم تطبيقات تكنولوجيا المعلومات", "Progress Pekerjaan Tim IT Application Support": "تقدم عمل فريق دعم تطبيقات تكنولوجيا المعلومات", "Quick Actions": "إجراءات سريعة", "Buat Ticket": "إنشاء تذكرة", "Lihat Semua": "عرض الكل", "Semua Status": "جميع الحالات", "To Do": "للقيام", "On Progress": "قيد التنفيذ", "Completed": "مكتمل", "Semua Prioritas": "جميع الأولويات", "High": "عالي", "Medium": "متوسط", "Low": "منخفض", "Cari tiket...": "البحث عن التذاكر...", "Judul Tiket": "عنوان التذكرة", "Layanan": "الخدمة", "Status": "الحالة", "Prioritas": "الأولوية", "Dibuat": "تم الإنشاء", "Loading tickets...": "جاري تحميل التذاكر...", "Tidak ada tiket ditemukan": "لم يتم العثور على تذاكر", "Belum di-assign": "غير معين", "Menampilkan": "عرض", "dari": "من", "tiket": "تذاكر", "Sen": "إثن", "Sel": "ثلا", "Rab": "أرب", "Kam": "خمي", "Jum": "جمع", "Sab": "سبت", "Min": "أحد", "Agenda": "جدول الأعمال", "agenda": "أجندة", "Tidak ada tiket dibuat": "لم يتم إنشاء أي تذاكر", "Pilih tanggal lain atau buat tiket baru.": "حدد تاريخاً آخر أو قم بإنشاء تذكرة جديدة.", "Task diselesaikan": "اكتملت المهمة", "Task diproses": "المهمة قيد المعالجة", "Prioritas tinggi": "أولوية عالية", "Ticket baru / To Do": "تذكرة جديدة / للقيام", "Tinggi": "عالي", "Sedang": "متوسط", "Rendah": "منخفض",
    "Manajemen Tiket": "إدارة التذاكر", "Daftar seluruh tiket aktif dan riwayat penyelesaian.": "قائمة بجميع التذاكر النشطة وسجل الإنجاز.", "Refresh Data": "تحديث البيانات", "Buat Tiket Baru": "إنشاء تذكرة جديدة", "Selesai": "مكتمل", "Cari subject, deskripsi, atau ID...": "البحث عن الموضوع، الوصف، أو المعرف...", "Semua Layanan": "جميع الخدمات", "Semua PIC": "جميع المسؤولين", "Subject": "الموضوع", "Aksi": "إجراء", "Tidak ada tiket yang ditemukan.": "لم يتم العثور على تذاكر.", "Coba sesuaikan filter atau pencarian Anda.": "حاول ضبط الفلاتر أو البحث.", "Lihat Solusi": "عرض الحل", "Selesaikan Tiket": "حل التذكرة", "Tiket yang sudah selesai tidak dapat diedit": "لا يمكن تعديل التذاكر المكتملة", "Edit Ticket": "تعديل التذكرة", "Hapus Tiket": "حذف التذكرة", "Tidak ada deskripsi": "لا يوجد وصف", "Tanggal": "التاريخ", "Tiket To Do": "تذاكر للقيام", "Tiket belum/sedang penanganan": "التذاكر قيد الانتظار أو التنفيذ", "Total tiket diselesaikan": "إجمالي التذاكر المكتملة", "Butuh tindakan segera": "يتطلب إجراء فوري", "Keseluruhan tiket": "جميع التذاكر"
  },
  Cina: {
    Dashboard: "仪表板", Ticket: "工单", "Recurring Task": "定期任务", Laporan: "报告", "Knowledge Base": "知识库", PIC: "负责人", "Chatbot AI": "AI聊天机器人", Pengaturan: "设置", Keluar: "退出",
    "Tiket Aktif": "活跃工单", "Tiket Selesai": "已完成工单", "Prioritas Tinggi": "高优先级", "Total Laporan": "总报告", "Distribusi Prioritas": "优先级分布", "Riwayat Aktivitas Terkini": "最近活动", "Ticket Terbaru": "最新工单",
    "Preferensi Tampilan": "显示偏好", Tema: "主题", Terang: "明亮", Gelap: "暗黑", "Bahasa Aplikasi": "应用语言", "Notifikasi Sistem": "系统通知", "Data & Aplikasi": "数据和应用", "Tentang Aplikasi": "关于应用", Reset: "重置", Bersihkan: "清除",
    "Welcome,": "欢迎，", "IT Application Support Team": "IT 应用支持团队", "Progress Pekerjaan Tim IT Application Support": "IT 应用支持团队工作进度", "Quick Actions": "快速操作", "Buat Ticket": "创建工单", "Lihat Semua": "查看全部", "Semua Status": "所有状态", "To Do": "待办", "On Progress": "进行中", "Completed": "已完成", "Semua Prioritas": "所有优先级", "High": "高", "Medium": "中", "Low": "低", "Cari tiket...": "搜索工单...", "Judul Tiket": "工单标题", "Layanan": "服务", "Status": "状态", "Prioritas": "优先级", "Dibuat": "创建于", "Loading tickets...": "加载工单中...", "Tidak ada tiket ditemukan": "未找到工单", "Belum di-assign": "未分配", "Menampilkan": "显示", "dari": "共", "tiket": "工单", "Sen": "一", "Sel": "二", "Rab": "三", "Kam": "四", "Jum": "五", "Sab": "六", "Min": "日", "Agenda": "日程", "agenda": "日程安排", "Tidak ada tiket dibuat": "未创建工单", "Pilih tanggal lain atau buat tiket baru.": "选择其他日期或创建新工单。", "Task diselesaikan": "任务完成", "Task diproses": "任务处理中", "Prioritas tinggi": "高优先级", "Ticket baru / To Do": "新工单 / 待办", "Tinggi": "高", "Sedang": "中", "Rendah": "低",
    "Manajemen Tiket": "工单管理", "Daftar seluruh tiket aktif dan riwayat penyelesaian.": "所有活动工单和完成记录列表。", "Refresh Data": "刷新数据", "Buat Tiket Baru": "创建新工单", "Selesai": "已完成", "Cari subject, deskripsi, atau ID...": "搜索主题、描述或 ID...", "Semua Layanan": "所有服务", "Semua PIC": "所有负责人", "Subject": "主题", "Aksi": "操作", "Tidak ada tiket yang ditemukan.": "未找到工单。", "Coba sesuaikan filter atau pencarian Anda.": "尝试调整过滤器或搜索。", "Lihat Solusi": "查看解决方案", "Selesaikan Tiket": "解决工单", "Tiket yang sudah selesai tidak dapat diedit": "已完成的工单无法编辑", "Edit Ticket": "编辑工单", "Hapus Tiket": "删除工单", "Tidak ada deskripsi": "没有描述", "Tanggal": "日期", "Tiket To Do": "待办工单", "Tiket belum/sedang penanganan": "等待处理或处理中的工单", "Total tiket diselesaikan": "总共完成的工单", "Butuh tindakan segera": "需要立即处理", "Keseluruhan tiket": "所有工单"
  },
  Jerman: {
    Dashboard: "Dashboard", Ticket: "Ticket", "Recurring Task": "Wiederkehrende Aufgabe", Laporan: "Berichte", "Knowledge Base": "Wissensdatenbank", PIC: "Zuständiger", "Chatbot AI": "KI-Chatbot", Pengaturan: "Einstellungen", Keluar: "Abmelden",
    "Tiket Aktif": "Aktive Tickets", "Tiket Selesai": "Abgeschlossene Tickets", "Prioritas Tinggi": "Hohe Priorität", "Total Laporan": "Gesamtberichte", "Distribusi Prioritas": "Prioritätsverteilung", "Riwayat Aktivitas Terkini": "Letzte Aktivität", "Ticket Terbaru": "Neueste Tickets",
    "Preferensi Tampilan": "Anzeigeeinstellungen", Tema: "Thema", Terang: "Hell", Gelap: "Dunkel", "Bahasa Aplikasi": "App-Sprache", "Notifikasi Sistem": "Systembenachrichtigungen", "Data & Aplikasi": "Daten & App", "Tentang Aplikasi": "Über die App", Reset: "Zurücksetzen", Bersihkan: "Löschen",
    "Welcome,": "Willkommen,", "IT Application Support Team": "IT-Anwendungsunterstützungsteam", "Progress Pekerjaan Tim IT Application Support": "Arbeitsfortschritt des IT-Support-Teams", "Quick Actions": "Schnellaktionen", "Buat Ticket": "Ticket erstellen", "Lihat Semua": "Alle anzeigen", "Semua Status": "Alle Status", "To Do": "Zu erledigen", "On Progress": "In Bearbeitung", "Completed": "Abgeschlossen", "Semua Prioritas": "Alle Prioritäten", "High": "Hoch", "Medium": "Mittel", "Low": "Niedrig", "Cari tiket...": "Tickets suchen...", "Judul Tiket": "Ticket-Titel", "Layanan": "Dienst", "Status": "Status", "Prioritas": "Priorität", "Dibuat": "Erstellt", "Loading tickets...": "Tickets werden geladen...", "Tidak ada tiket ditemukan": "Keine Tickets gefunden", "Belum di-assign": "Nicht zugewiesen", "Menampilkan": "Zeige", "dari": "von", "tiket": "Tickets", "Sen": "Mo", "Sel": "Di", "Rab": "Mi", "Kam": "Do", "Jum": "Fr", "Sab": "Sa", "Min": "So", "Agenda": "Agenda", "agenda": "Agenda", "Tidak ada tiket dibuat": "Keine Tickets erstellt", "Pilih tanggal lain atau buat tiket baru.": "Anderes Datum wählen oder neues Ticket erstellen.", "Task diselesaikan": "Aufgabe abgeschlossen", "Task diproses": "Aufgabe in Bearbeitung", "Prioritas tinggi": "Hohe Priorität", "Ticket baru / To Do": "Neues Ticket / Zu erledigen", "Tinggi": "Hoch", "Sedang": "Mittel", "Rendah": "Niedrig",
    "Manajemen Tiket": "Ticketverwaltung", "Daftar seluruh tiket aktif dan riwayat penyelesaian.": "Liste aller aktiven Tickets und Abschlussverlauf.", "Refresh Data": "Daten aktualisieren", "Buat Tiket Baru": "Neues Ticket erstellen", "Selesai": "Abgeschlossen", "Cari subject, deskripsi, atau ID...": "Betreff, Beschreibung oder ID suchen...", "Semua Layanan": "Alle Dienste", "Semua PIC": "Alle PICs", "Subject": "Betreff", "Aksi": "Aktion", "Tidak ada tiket yang ditemukan.": "Keine Tickets gefunden.", "Coba sesuaikan filter atau pencarian Anda.": "Passen Sie Ihre Filter oder Suche an.", "Lihat Solusi": "Lösung ansehen", "Selesaikan Tiket": "Ticket lösen", "Tiket yang sudah selesai tidak dapat diedit": "Abgeschlossene Tickets können nicht bearbeitet werden", "Edit Ticket": "Ticket bearbeiten", "Hapus Tiket": "Ticket löschen", "Tidak ada deskripsi": "Keine Beschreibung", "Tanggal": "Datum", "Tiket To Do": "Tickets zu erledigen", "Tiket belum/sedang penanganan": "Tickets in Warteschlange oder Bearbeitung", "Total tiket diselesaikan": "Gesamte abgeschlossene Tickets", "Butuh tindakan segera": "Erfordert sofortige Maßnahme", "Keseluruhan tiket": "Alle Tickets"
  },
  Perancis: {
    Dashboard: "Tableau de Bord", Ticket: "Billet", "Recurring Task": "Tâche Récurrente", Laporan: "Rapports", "Knowledge Base": "Base de Connaissances", PIC: "Responsable", "Chatbot AI": "Chatbot IA", Pengaturan: "Paramètres", Keluar: "Se Déconnecter",
    "Tiket Aktif": "Billets Actifs", "Tiket Selesai": "Billets Terminés", "Prioritas Tinggi": "Haute Priorité", "Total Laporan": "Total des Rapports", "Distribusi Prioritas": "Répartition des Priorités", "Riwayat Aktivitas Terkini": "Activité Récente", "Ticket Terbaru": "Derniers Billets",
    "Preferensi Tampilan": "Préférences d'Affichage", Tema: "Thème", Terang: "Clair", Gelap: "Sombre", "Bahasa Aplikasi": "Langue de l'Application", "Notifikasi Sistem": "Notifications Système", "Data & Aplikasi": "Données et Application", "Tentang Aplikasi": "À propos de l'App", Reset: "Réinitialiser", Bersihkan: "Effacer",
    "Welcome,": "Bienvenue,", "IT Application Support Team": "Équipe de Support Informatique", "Progress Pekerjaan Tim IT Application Support": "Avancement des Travaux du Support", "Quick Actions": "Actions Rapides", "Buat Ticket": "Créer un Billet", "Lihat Semua": "Voir Tout", "Semua Status": "Tous les Statuts", "To Do": "À Faire", "On Progress": "En Cours", "Completed": "Terminé", "Semua Prioritas": "Toutes les Priorités", "High": "Haut", "Medium": "Moyen", "Low": "Bas", "Cari tiket...": "Rechercher des billets...", "Judul Tiket": "Titre du Billet", "Layanan": "Service", "Status": "Statut", "Prioritas": "Priorité", "Dibuat": "Créé", "Loading tickets...": "Chargement des billets...", "Tidak ada tiket ditemukan": "Aucun billet trouvé", "Belum di-assign": "Non attribué", "Menampilkan": "Affichage de", "dari": "sur", "tiket": "billets", "Sen": "Lun", "Sel": "Mar", "Rab": "Mer", "Kam": "Jeu", "Jum": "Ven", "Sab": "Sam", "Min": "Dim", "Agenda": "Agenda", "agenda": "agenda(s)", "Tidak ada tiket dibuat": "Aucun billet créé", "Pilih tanggal lain atau buat tiket baru.": "Choisissez une autre date ou créez un nouveau billet.", "Task diselesaikan": "Tâche terminée", "Task diproses": "Tâche en cours", "Prioritas tinggi": "Haute priorité", "Ticket baru / To Do": "Nouveau billet / À faire", "Tinggi": "Haut", "Sedang": "Moyen", "Rendah": "Bas",
    "Manajemen Tiket": "Gestion des Billets", "Daftar seluruh tiket aktif dan riwayat penyelesaian.": "Liste de tous les billets actifs et historique.", "Refresh Data": "Actualiser les Données", "Buat Tiket Baru": "Créer un Nouveau Billet", "Selesai": "Terminé", "Cari subject, deskripsi, atau ID...": "Rechercher sujet, description ou ID...", "Semua Layanan": "Tous les Services", "Semua PIC": "Tous les Responsables", "Subject": "Sujet", "Aksi": "Action", "Tidak ada tiket yang ditemukan.": "Aucun billet trouvé.", "Coba sesuaikan filter atau pencarian Anda.": "Essayez d'ajuster vos filtres ou recherche.", "Lihat Solusi": "Voir la Solution", "Selesaikan Tiket": "Résoudre le Billet", "Tiket yang sudah selesai tidak dapat diedit": "Les billets terminés ne peuvent être modifiés", "Edit Ticket": "Modifier le Billet", "Hapus Tiket": "Supprimer le Billet", "Tidak ada deskripsi": "Aucune description", "Tanggal": "Date", "Tiket To Do": "Billets à faire", "Tiket belum/sedang penanganan": "Billets en attente ou en cours", "Total tiket diselesaikan": "Total des billets terminés", "Butuh tindakan segera": "Nécessite une action immédiate", "Keseluruhan tiket": "Tous les billets"
  },
  Jawa: {
    Dashboard: "Dasbor", Ticket: "Tiket", "Recurring Task": "Tugas Rutin", Laporan: "Laporan", "Knowledge Base": "Pusat Ilmu", PIC: "Penanggung Jawab", "Chatbot AI": "Robot Obrolan", Pengaturan: "Pengaturan", Keluar: "Metu",
    "Tiket Aktif": "Tiket Urip", "Tiket Selesai": "Tiket Rampung", "Prioritas Tinggi": "Prioritas Dhuwur", "Total Laporan": "Gunggung Laporan", "Distribusi Prioritas": "Sebaran Prioritas", "Riwayat Aktivitas Terkini": "Riwayat Paling Anyar", "Ticket Terbaru": "Tiket Anyar",
    "Preferensi Tampilan": "Setelan Tampilan", Tema: "Latar", Terang: "Padhang", Gelap: "Peteng", "Bahasa Aplikasi": "Basa Aplikasi", "Notifikasi Sistem": "Péling Sistem", "Data & Aplikasi": "Data & Aplikasi", "Tentang Aplikasi": "Babagan Aplikasi", Reset: "Balèni", Bersihkan: "Resiki",
    "Welcome,": "Sugeng Rawuh,", "IT Application Support Team": "Tim Bantuan Aplikasi IT", "Progress Pekerjaan Tim IT Application Support": "Pangrembakan Pakaryan Tim IT", "Quick Actions": "Tindak Gelis", "Buat Ticket": "Gawe Tiket", "Lihat Semua": "Deleng Kabeh", "Semua Status": "Kabeh Status", "To Do": "Bakal Digawe", "On Progress": "Lagi Mlaku", "Completed": "Rampung", "Semua Prioritas": "Kabeh Prioritas", "High": "Dhuwur", "Medium": "Sedheng", "Low": "Cendhek", "Cari tiket...": "Golek tiket...", "Judul Tiket": "Judul Tiket", "Layanan": "Layanan", "Status": "Status", "Prioritas": "Prioritas", "Dibuat": "Digawe", "Loading tickets...": "Loading tiket...", "Tidak ada tiket ditemukan": "Ora ana tiket ditemokake", "Belum di-assign": "Durung diwenehke", "Menampilkan": "Nampilake", "dari": "saka", "tiket": "tiket", "Sen": "Sen", "Sel": "Sel", "Rab": "Reb", "Kam": "Kem", "Jum": "Jum", "Sab": "Sab", "Min": "Min", "Agenda": "Acara", "agenda": "acara", "Tidak ada tiket dibuat": "Ora ana tiket digawe", "Pilih tanggal lain atau buat tiket baru.": "Pilih tanggal liyane utawa gawe tiket anyar.", "Task diselesaikan": "Tugas wis rampung", "Task diproses": "Tugas lagi diproses", "Prioritas tinggi": "Prioritas dhuwur", "Ticket baru / To Do": "Tiket anyar / Bakal digawe", "Tinggi": "Dhuwur", "Sedang": "Sedheng", "Rendah": "Cendhek",
    "Manajemen Tiket": "Pangaturan Tiket", "Daftar seluruh tiket aktif dan riwayat penyelesaian.": "Daftar kabeh tiket sing mlaku lan riwayat rampung.", "Refresh Data": "Muat Ulang Data", "Buat Tiket Baru": "Gawe Tiket Anyar", "Selesai": "Rampung", "Cari subject, deskripsi, atau ID...": "Golek subjek, katrangan, utawa ID...", "Semua Layanan": "Kabeh Layanan", "Semua PIC": "Kabeh PIC", "Subject": "Subjek", "Aksi": "Aksi", "Tidak ada tiket yang ditemukan.": "Ora ana tiket sing ditemokake.", "Coba sesuaikan filter atau pencarian Anda.": "Coba atur filter utawa panjenengan golek maneh.", "Lihat Solusi": "Deleng Solusi", "Selesaikan Tiket": "Rampungake Tiket", "Tiket yang sudah selesai tidak dapat diedit": "Tiket sing wis rampung ora bisa diowahi", "Edit Ticket": "Owahi Tiket", "Hapus Tiket": "Busek Tiket", "Tidak ada deskripsi": "Ora ana katrangan", "Tanggal": "Tanggal", "Tiket To Do": "Tiket Bakal Digawe", "Tiket belum/sedang penanganan": "Tiket durung utawa lagi dicekel", "Total tiket diselesaikan": "Gunggung tiket rampung", "Butuh tindakan segera": "Butuh tindak gelis", "Keseluruhan tiket": "Kabeh tiket"
  }
};

const content = 'export const translations = ' + JSON.stringify(data, null, 2) + ';';
fs.writeFileSync('src/utils/translations.js', content, 'utf-8');
console.log('Translations completely overwritten and populated!');
